server:
  port: 8102
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8103
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=dj, success
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    # 设置应用的名称
    name: dubbo-springboot-demo
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 8889
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848